export const RESTAURANT_INFO = {
  name: "MyWay",
  tagline: "A Symphony of Luxury and Taste",
  address: "Molyko, UB Junction, Lacave Building, Buea, Cameroon",
  phone: "+237 6 51 37 18 00",
  email: "emperordante123@gmail.com",
  whatsapp: "https://wa.me/237651371800",
  hours: {
    weekdays: "12:00 PM - 11:00 PM",
    weekends: "12:00 PM - 12:00 AM",
  },
  socials: {
    instagram: "https://instagram.com/myway_restaurant",
    facebook: "https://facebook.com/myway_restaurant",
    tiktok: "https://www.tiktok.com/@myway.restaurant",
    tripadvisor: "https://tripadvisor.com/myway_restaurant",
  },
};

export const RESERVATION_SLOTS = [
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
  "8:30 PM",
  "9:00 PM",
  "9:30 PM",
  "10:00 PM",
];

export interface MenuItem {
  id: string;
  nameEn: string;
  nameFr: string;
  descriptionEn: string;
  descriptionFr: string;
  price: number;
  category: string;
  image?: string; // Cloudinary public ID
  dietary?: string[];
  featured?: boolean;
}

/**
 * Localized Fallback Menu Items Catalog
 *
 * NOTE FOR IMAGES:
 * The 'image' field corresponds directly to the Cloudinary asset's Public ID.
 * When you upload new food photos to Cloudinary, simply replace these string
 * values (e.g. 'fine_plating') with the public IDs of your uploaded images.
 * If you leave it empty or delete it, the card automatically falls back to your logo.
 */
export const FALLBACK_MENU: MenuItem[] = [
  // Starters & Appetizers
  {
    id: "starter-1",
    nameEn: "Shrimp Tempura",
    nameFr: "Tempura de Crevettes",
    descriptionEn:
      "Crispy seasoned shrimps served with home-style spicy dipping sauce.",
    descriptionFr:
      "Crevettes croustillantes assaisonnées servies avec une sauce piquante maison.",
    price: 3000,
    category: "starters",
    image: "shrimp_tempura",
    dietary: ["Seafood"],
    featured: true,
  },
  {
    id: "starter-2",
    nameEn: "Onion Rings",
    nameFr: "Rondelles d’Oignon",
    descriptionEn:
      "Crispy golden onion rings to serve as a starter or a bite on the go.",
    descriptionFr:
      "Rondelles d’oignons dorées et croustillantes pour commencer ou grignoter.",
    price: 1000,
    category: "starters",
    image: "onion_rings",
  },
  // Salads
  {
    id: "salad-1",
    nameEn: "Vegetable Salad",
    nameFr: "Salade de Légumes",
    descriptionEn:
      "Raw seasonal vegetables tossed with vinegar, mustard dressing, and herbs.",
    descriptionFr:
      "Légumes crus de saison assaisonnés de vinaigre, moutarde et fines herbes.",
    price: 2000,
    category: "salads",
    image: "vegetable_salade",
    dietary: ["Vegetarian", "Vegan"],
  },
  {
    id: "salad-2",
    nameEn: "Avocado Salad",
    nameFr: "Salade d’Avocat",
    descriptionEn:
      "Fresh avocado cubes, cherry tomatoes, cucumbers, mixed greens with vinaigrette.",
    descriptionFr:
      "Avocats frais, tomates cerises, concombres, salades vertes avec vinaigrette.",
    price: 3000,
    category: "avocado_salade",
    image: "wine_cellar",
    dietary: ["Vegetarian", "Gluten-Free"],
  },
  // Burgers
  {
    id: "burger-1",
    nameEn: "Burger (Double)",
    nameFr: "Burger (Double)",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "burgers",
    image: "burger_double",
    featured: true,
  },
  {
    id: "burger-2",
    nameEn: "Burger (Simple)",
    nameFr: "Burger (Simple)",
    descriptionEn: "",
    descriptionFr: "",
    price: 1500,
    category: "burgers",
    image: "burger_simple",
    featured: true,
  },
  {
    id: "burger-3",
    nameEn: "Egg and Cheeseburger",
    nameFr: "Œufs et le Cheeseburger",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "burgers",
    image: "egg_and_cheeseburger",
    featured: true,
  },
  {
    id: "burger-4",
    nameEn: "Double Cheese Burger",
    nameFr: "Double Cheese Burger",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "burgers",
    image: "double_cheese_burger",
    featured: true,
  },
  {
    id: "burger-5",
    nameEn: "Chicken Cheese Burger",
    nameFr: "Chicken Cheese Burger",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "burgers",
    image: "chicken_cheese_burger",
    featured: true,
  },
  {
    id: "burger-6",
    nameEn: "Cheeseburger",
    nameFr: "Cheeseburger",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "burgers",
    image: "cheeseburger",
    featured: true,
  },
  // Pizzas
  {
    id: "pizza-1",
    nameEn: "Shrimp Pizza SMALL",
    nameFr: "Pizza aux crevettes PETIT",
    descriptionEn: "",
    descriptionFr: "",
    price: 6000,
    category: "pizzas",
    image: "shrimp_pizza_small",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-2",
    nameEn: "Shrimp Pizza MEDIUM",
    nameFr: "Pizza aux crevettes MOYENNE",
    descriptionEn: "",
    descriptionFr: "",
    price: 9000,
    category: "pizzas",
    image: "shrimp_pizza_medium",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-3",
    nameEn: "Shrimp Pizza LARGE",
    nameFr: "Pizza aux crevettes GRANDE",
    descriptionEn: "",
    descriptionFr: "",
    price: 12000,
    category: "pizzas",
    image: "shrimp_pizza_large",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-4",
    nameEn: "Minced Beef Pizza SMALL",
    nameFr: "Pizza aux viande hachée PETIT",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "pizzas",
    image: "minced_beef_pizza_small",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-5",
    nameEn: "Minced Beef Pizza MEDIUM",
    nameFr: "Pizza aux viande hachée MOYENNE",
    descriptionEn: "",
    descriptionFr: "",
    price: 7500,
    category: "pizzas",
    image: "minced_beef_pizza_medium",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-6",
    nameEn: "Minced Beef Pizza LARGE",
    nameFr: "Pizza aux viande hachée GRANDE",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "pizzas",
    image: "minced_beef_pizza_large",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-7",
    nameEn: "Ham (Jambon) Pizza SMALL",
    nameFr: "Pizza Jambon PETIT",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "pizzas",
    image: "ham_jambon_pizza_small",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-8",
    nameEn: "Ham (Jambon) Pizza MEDIUM",
    nameFr: "Pizza Jambon MOYENNE",
    descriptionEn: "",
    descriptionFr: "",
    price: 7500,
    category: "pizzas",
    image: "ham_jambon_pizza_medium",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-9",
    nameEn: "Ham (Jambon) Pizza LARGE",
    nameFr: "Pizza Jambon GRANDE",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "pizzas",
    image: "ham_jambon_pizza_large",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-10",
    nameEn: "Chicken Pizza LARGE",
    nameFr: "Pizza au Poulet GRANDE",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "pizzas",
    image: "chicken_pizza_large",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-11",
    nameEn: "Chicken Pizza MEDIUM",
    nameFr: "Pizza au Poulet MOYENNE",
    descriptionEn: "",
    descriptionFr: "",
    price: 7500,
    category: "pizzas",
    image: "chicken_pizza_medium",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-12",
    nameEn: "Chicken Pizza SMALL",
    nameFr: "Pizza au Poulet PETIT",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "pizzas",
    image: "chicken_pizza_small",
    dietary: ["Vegetarian"],
  },
  {
    id: "pizza-13",
    nameEn: "Myway Pizza Wrap",
    nameFr: "Wrap Pizza Myway",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "pizzas",
    image: "myway_pizza_wrap",
    dietary: ["Vegetarian"],
  },
  // Pasta & Rice
  {
    id: "pasta-1",
    nameEn: "MyWay Thai Jollof Beef, Chicken and Shrimp",
    nameFr: "Jollof Thai MyWay Viande, Poulet et Crevette",
    descriptionEn: "Thai Jollof with spiced beef, chicken and shrimps",
    descriptionFr: "Jollof Thaï aux boeuf, poulet et crevettes épicés",
    price: 6000,
    category: "pasta_rice",
    image: "myway_thai_jollof_beef_chicken_and_shrimps",
    dietary: ["Seafood"],
  },
  {
    id: "pasta-2",
    nameEn: "MyWay Thai Jollof Beef and Chicken",
    nameFr: "Jollof Thai MyWay Viande et Poulet",
    descriptionEn: "Thai Jollof with spiced beef and chicken breast",
    descriptionFr: "Jollof Thaï aux boeuf et poulet épicés",
    price: 5500,
    category: "pasta_rice",
    image: "myway_thai_jollof_beef_and_chicken",
  },
  {
    id: "pasta-3",
    nameEn: "Myway Thai Jollof Chicken",
    nameFr: "Jollof Thai MyWay Poulet",
    descriptionEn: "Thai Jollof with spiced chicken ",
    descriptionFr: "Jollof Thaï au poulet épicé",
    price: 4500,
    category: "pasta_rice",
    image: "myway_thai_jollof_chicken",
  },
  {
    id: "pasta-4",
    nameEn: "MyWay Thai Jollof Beef",
    nameFr: "Jollof Thai MyWay Viande",
    descriptionEn: "Thai Jollof with spiced beef",
    descriptionFr: "Jollof Thaï aux boeuf épicé",
    price: 4500,
    category: "pasta_rice",
    image: "myway_thai_jollof_beef",
  },
  {
    id: "pasta-5",
    nameEn: "Creamy Chicken Fussilli",
    nameFr: "Fussili au poulet crémeux",
    descriptionEn: "",
    descriptionFr: "",
    price: 6000,
    category: "pasta_rice",
    image: "creamy_chicken_fussilli",
  },
  {
    id: "pasta-6",
    nameEn: "Lasagna",
    nameFr: "Lasagne",
    descriptionEn: "",
    descriptionFr: "",
    price: 6500,
    category: "pasta_rice",
    image: "lasagna",
  },
  {
    id: "pasta-7",
    nameEn: "Bolognese Pasta",
    nameFr: "Pâtes Bolognaises",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "pasta_rice",
    image: "bolognese_pasta",
    dietary: ["Seafood"],
  },
  // Chicken Dishes
  {
    id: "chicken-1",
    nameEn: "Chopped Chicken Breast",
    nameFr: "Poitrine de Poulet Hachée",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "chicken",
    image: "chopped_chiken_breast",
  },
  {
    id: "chicken-2",
    nameEn: "Poulet DG (1/4 Chicken)",
    nameFr: "Poulet DG (1/4 Poulet)",
    descriptionEn: "",
    descriptionFr: "",
    price: 6000,
    category: "chicken",
    image: "poulet_dg_0.25_chicken",
  },
  {
    id: "chicken-3",
    nameEn: "Crispy Chicken Whole",
    nameFr: "Poulet Frit Entier",
    descriptionEn: "Whole chicken served in pieces",
    descriptionFr: "Poulet entier servi en morceaux",
    price: 17000,
    category: "chicken",
    image: "crispy_chicken_whole",
  },
  {
    id: "chicken-4",
    nameEn: "Crispy Chicken Plate ",
    nameFr: "Poulet Frit Croustillant ",
    descriptionEn: "Drumstick,Thigh and wing (fries not included)",
    descriptionFr: "Pilon, Cuisse et Aile (frites non comprises)",
    price: 5000,
    category: "chicken",
    image: "crispy_chicken_plate",
  },
  {
    id: "chicken-5",
    nameEn: "1/4 Grilled Chicken",
    nameFr: "Poulet Grillé 1/4",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "chicken",
    image: "0.25_grilled_chicken",
  },
  {
    id: "chicken-6",
    nameEn: "Poulet DG (1/2 Chicken)",
    nameFr: "Poulet DG (1/2 Poulet)",
    descriptionEn: "",
    descriptionFr: "",
    price: 11000,
    category: "chicken",
    image: "poulet_dg_0.50_chicken",
  },
  {
    id: "chicken-7",
    nameEn: "Poulet DG (Whole Chicken)",
    nameFr: "Poulet DG (Poulet entier)",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "chicken",
    image: "poulet_dg_whole_chicken",
  },
  {
    id: "chicken-8",
    nameEn: "Chicken Tenders",
    nameFr: "Poulet pané",
    descriptionEn: "Crispy spiced chicken breast (fries not included)",
    descriptionFr: "Lanières de poulet pané (frites non comprises)",
    price: 5000,
    category: "chicken",
    image: "chicken_tenders",
  },
  // Beef, Pork & Lamb
  {
    id: "beef-1",
    nameEn: "Pork (Grilled Or Sautéed)",
    nameFr: "Porc (Grillé Ou Sauté)",
    descriptionEn: "Choose Grilled or Sautéed",
    descriptionFr: "Choisissez grillé ou sauté",
    price: 5000,
    category: "beef_lamb",
    image: "pork_grilled_or_sauteed",
    featured: true,
  },
  {
    id: "beef-2",
    nameEn: "Live Tomahawk Steak Experience 🔥🍖 (GROUP MEAL)",
    nameFr: "Expérience Tomahawk au feu 🔥🍖 (POUR GROUPE)",
    descriptionEn: "",
    descriptionFr: "",
    price: 35000,
    category: "beef_lamb",
    image: "live_tomahawk_steak_experience",
    featured: true,
  },
  {
    id: "beef-3",
    nameEn: "Porc Ham Steak / Noix De Porc",
    nameFr: "Porc Ham Steak / Noix De Porc",
    descriptionEn: "",
    descriptionFr: "",
    price: 6500,
    category: "beef_lamb",
    image: "porc_ham_steak",
    featured: true,
  },
  {
    id: "beef-4",
    nameEn: "Meatballs",
    nameFr: "Boulettes De Viande",
    descriptionEn: "",
    descriptionFr: "",
    price: 4500,
    category: "beef_lamb",
    image: "meatballs",
    featured: true,
  },
  {
    id: "beef-5",
    nameEn: "Lamb Chops",
    nameFr: "Côtelettes d'agneau",
    descriptionEn: "",
    descriptionFr: "",
    price: 7500,
    category: "beef_lamb",
    image: "lambchops",
    featured: true,
  },
  {
    id: "beef-6",
    nameEn: "Beef Fillet",
    nameFr: "Filet De Boeuf",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "beef_lamb",
    image: "beef_fillet",
    featured: true,
  },
  // Seafood
  {
    id: "seafood-1",
    nameEn: "Catfish Ndomba (Machoiron)",
    nameFr: "Ndomba de Poisson (Machoiron)",
    descriptionEn: "",
    descriptionFr: "",
    price: 6500,
    category: "seafood",
    image: "catfish_ndomba",
    dietary: ["Seafood", "Gluten-Free"],
  },
  {
    id: "seafood-2",
    nameEn: "Prawns (Gambas)",
    nameFr: "Crevettes (Gambas)",
    descriptionEn: "",
    descriptionFr: "",
    price: 12000,
    category: "seafood",
    image: "prawns",
    dietary: ["Seafood", "Gluten-Free"],
  },
  {
    id: "seafood-3",
    nameEn: "Sea Bass XL (Oven Grilled)",
    nameFr: "Bar XL (Grillé au four)",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "seafood",
    image: "sea_bass_xl",
    dietary: ["Seafood", "Gluten-Free"],
  },
  {
    id: "seafood-4",
    nameEn: "Shrimp",
    nameFr: "Crevettes",
    descriptionEn: "",
    descriptionFr: "",
    price: 6000,
    category: "seafood",
    image: "shrimp",
    dietary: ["Seafood", "Gluten-Free"],
  },
  {
    id: "seafood-5",
    nameEn: "Captain Fish Fillet Grilled",
    nameFr: "Pavé de Capitaine Grillé",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "seafood",
    image: "captain_fish_fillet_grilled",
    dietary: ["Seafood", "Gluten-Free"],
  },
  {
    id: "seafood-6",
    nameEn: "Sea Bass (Oven Grilled)",
    nameFr: "Bar du Chili Grillé",
    descriptionEn: "",
    descriptionFr: "",
    price: 6500,
    category: "seafood",
    image: "sea_bass",
    dietary: ["Seafood", "Gluten-Free"],
  },
  // Local Specialities
  {
    id: "local-1",
    nameEn: "Ndole Royale",
    nameFr: "Ndolè Royale",
    descriptionEn: "",
    descriptionFr: "",
    price: 6000,
    category: "local",
    image: "ndole_royale",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },
  {
    id: "local-2",
    nameEn: "Snails Sauce",
    nameFr: "Sauce Escargot",
    descriptionEn: "With white rice or plantain fries",
    descriptionFr: "avec du riz blanc ou des frites de plantain",
    price: 6000,
    category: "local",
    image: "snails_sauce",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },
  {
    id: "local-3",
    nameEn: "Liver Sauce",
    nameFr: "Sauce Foie",
    descriptionEn: "With white rice or plantain fries",
    descriptionFr: "avec du riz blanc ou des frites de plantain",
    price: 5000,
    category: "local",
    image: "liver_sauce",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },
  {
    id: "local-4",
    nameEn: "Kidney Sauce",
    nameFr: "Sauce Reine",
    descriptionEn: "With white rice or plantain fries",
    descriptionFr: "avec du riz blanc ou des frites de plantain",
    price: 6000,
    category: "local",
    image: "kidney_sauce",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },
  {
    id: "local-5",
    nameEn: "Tripe (Towel) Sauce",
    nameFr: "Sauce Tripe",
    descriptionEn: "With white rice or plantain fries",
    descriptionFr: "avec du riz blanc ou des frites de plantain",
    price: 5000,
    category: "local",
    image: "tripe_sauce",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },
  {
    id: "local-6",
    nameEn: "Gizzard Sauce",
    nameFr: "Sauce Gésiers",
    descriptionEn: "With white rice or plantain fries",
    descriptionFr: "avec du riz blanc ou des frites de plantain",
    price: 5000,
    category: "local",
    image: "gizzard_sauce",
    dietary: ["Cameroonian Classic"],
    featured: true,
  },

  // Desserts
  {
    id: "dessert-1",
    nameEn: "Waffles With Nutella",
    nameFr: "Gaufre avec du Nutella",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "desserts",
    image: "waffle_with_nutella",
  },
  {
    id: "dessert-2",
    nameEn: "Lemon Tart",
    nameFr: "Tarte au Citron",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "desserts",
    image: "lemon_tart",
  },
  {
    id: "dessert-3",
    nameEn: "Service Birthday",
    nameFr: "Service Anniversaire",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "desserts",
    image: "service_birthday",
  },
  {
    id: "dessert-4",
    nameEn: "Chocolate Donuts",
    nameFr: "Beignets au Chocolat",
    descriptionEn: "",
    descriptionFr: "",
    price: 1000,
    category: "desserts",
    image: "chocolate_donuts",
  },
  {
    id: "dessert-5",
    nameEn: "Birthday Cake 15CM",
    nameFr: "Gâteau d'anniversaire 15cm",
    descriptionEn: "",
    descriptionFr: "",
    price: 10000,
    category: "desserts",
    image: "birthday_cake_15cm",
  },
  {
    id: "dessert-6",
    nameEn: "Opera Cake",
    nameFr: "Gâteau Opéra",
    descriptionEn: "",
    descriptionFr: "",
    price: 3000,
    category: "desserts",
    image: "opera_cake",
  },
  {
    id: "dessert-7",
    nameEn: "Chocolate Bean",
    nameFr: "Haricot Chocolat",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "desserts",
    image: "chocolate_bean",
  },
  {
    id: "dessert-8",
    nameEn: "Vanilla Bean",
    nameFr: "Gousse de Vanille",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "desserts",
    image: "vanilla_bean",
  },
  {
    id: "dessert-9",
    nameEn: "Birthday Cake 25CM",
    nameFr: "Gâteau d'anniversaire 25cm",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "desserts",
    image: "birthday_cake_25cm",
  },
  {
    id: "dessert-10",
    nameEn: "Alexandra(Cake)",
    nameFr: "Alexandra(Gâteau)",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "desserts",
    image: "alexandra_cake",
  },
  {
    id: "dessert-11",
    nameEn: "Chocolate Cake",
    nameFr: "Gâteau au chocolat",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "desserts",
    image: "chocolate_cake",
  },
  {
    id: "dessert-12",
    nameEn: "Birthday Cake Double Stack",
    nameFr: "Gâteau d'anniversaire double stack",
    descriptionEn: "",
    descriptionFr: "",
    price: 35000,
    category: "desserts",
    image: "birthday_cake_double_stack",
  },
  {
    id: "dessert-13",
    nameEn: "Birthday Cake Classic",
    nameFr: "Gâteau d'anniversaire classic",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "desserts",
    image: "birthday_cake_classic",
  },
  {
    id: "dessert-14",
    nameEn: "Lava Cake with Vanilla Ice Cream",
    nameFr: "Gâteau au chocolat",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "desserts",
    image: "lava_cake_with_vanilla_icecream",
  },
  {
    id: "dessert-15",
    nameEn: "Red Velvet Cake",
    nameFr: "Gâteau Red Velvet",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "desserts",
    image: "red_velvet_cake",
  },
  {
    id: "dessert-16",
    nameEn: "Tiramisu",
    nameFr: "Tiramisu",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "desserts",
    image: "tiramisu",
  },
  {
    id: "dessert-17",
    nameEn: "Crepes with Nutella and Blueberry Sauce",
    nameFr: "Crêpes au Nutella et sauce aux myrtilles",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "desserts",
    image: "crepes_with_nutella_and_blueberry_sauce",
  },
  {
    id: "dessert-18",
    nameEn: "Caramel Cake",
    nameFr: "Gâteau au caramel",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "desserts",
    image: "caramel_cake",
  },

  // Ice Cream
  {
    id: "ice-cream-1",
    nameEn: "Cone",
    nameFr: "Cone",
    descriptionEn: "",
    descriptionFr: "",
    price: 300,
    category: "ice_cream",
    image: "cone",
  },
  {
    id: "ice-cream-2",
    nameEn: "Gelato Ice Cream",
    nameFr: "Glace au Gelato",
    descriptionEn: "",
    descriptionFr: "",
    price: 1000,
    category: "ice_cream",
    image: "gelato_ice_cream",
  },
  // Natural Fruit Juice
  {
    id: "fruit-juice-1",
    nameEn: "PASSION Fruit/Watermelon Cocktail (Freshly Pressed)",
    nameFr: "PASSION Fruit/Watermelon Cocktail (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "fruit_juice",
    image: "passion_fruit_1",
  },
  {
    id: "fruit-juice-2",
    nameEn: "PASSION Fruit/Pineapple/Watermelon Cocktail (Freshly Pressed)",
    nameFr: "PASSION Fruit/Pineapple/Watermelon Cocktail (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 3000,
    category: "fruit_juice",
    image: "passion_fruit_2",
  },
  {
    id: "fruit-juice-3",
    nameEn: "PASSION Fruit/Pineapple Cocktail (Freshly Pressed)",
    nameFr: "PASSION Fruit/Pineapple Cocktail (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 3000,
    category: "fruit_juice",
    image: "passion_fruit_3",
  },
  {
    id: "fruit-juice-4",
    nameEn: "Apple Juice (Freshly Pressed)",
    nameFr: "Jus de Pomme (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 3000,
    category: "fruit_juice",
    image: "apple_juice",
  },
  {
    id: "fruit-juice-5",
    nameEn: "Watermelon (Freshly Pressed)",
    nameFr: "Jus de Pastèque (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "fruit_juice",
    image: "apple_juice",
  },
  {
    id: "fruit-juice-6",
    nameEn: "Pineapple (Freshly Pressed)",
    nameFr: "Jus d’ananas (Pressé Fraîchement)",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "fruit_juice",
    image: "apple_juice",
  },
  // Cocktails & Shakes
  {
    id: "cocktails-shakes-1",
    nameEn: "Mount Fako On Fire",
    nameFr: "Mont Fako en Feu",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "mount_fako_on_fire",
  },
  {
    id: "cocktails-shakes-2",
    nameEn: "BOEING 1985",
    nameFr: "Boeing 1985",
    descriptionEn: "",
    descriptionFr: "",
    price: 4500,
    category: "cocktails_shakes",
    image: "boeing_1985",
  },
  {
    id: "cocktails-shakes-3",
    nameEn: "Pink Lady",
    nameFr: "Pink Lady",
    descriptionEn: "",
    descriptionFr: "",
    price: 3000,
    category: "cocktails_shakes",
    image: "pink_lady",
  },
  {
    id: "cocktails-shakes-4",
    nameEn: "Long Island Tea",
    nameFr: "Long Island Tea",
    descriptionEn: "",
    descriptionFr: "",
    price: 4500,
    category: "cocktails_shakes",
    image: "long_island_tea",
  },
  {
    id: "cocktails-shakes-5",
    nameEn: "Blue Lagoon",
    nameFr: "Blue Lagoon",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "cocktails_shakes",
    image: "blue_lagoon",
  },
  {
    id: "cocktails-shakes-6",
    nameEn: "Lemonade",
    nameFr: "Lemonade",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "cocktails_shakes",
    image: "lemonade",
  },
  {
    id: "cocktails-shakes-7",
    nameEn: "Green Paradise",
    nameFr: "Green Paradise",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "green_paradise",
  },
  {
    id: "cocktails-shakes-8",
    nameEn: "Upon Request (A La Demande)",
    nameFr: "A La Demande",
    descriptionEn: "",
    descriptionFr: "",
    price: 0,
    category: "cocktails_shakes",
    image: "upon_request",
  },
  {
    id: "cocktails-shakes-9",
    nameEn: "ZANZILAMOOD - Non Alcoholic",
    nameFr: "ZANZILAMOOD - Non Alcoholic",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "cocktails_shakes",
    image: "zanzilamood",
  },
  {
    id: "cocktails-shakes-10",
    nameEn: "TOM COLLINS (Gin, Lemon Juice, Syrup,Soda)",
    nameFr: "TOM COLLINS (Gin, Lemon Juice, Syrup,Soda)",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "tom_collins",
  },
  {
    id: "cocktails-shakes-11",
    nameEn: "Tequila Sunrise (Tequila, Orange Juice,Syrup)",
    nameFr: "Tequila Sunrise (Tequila, Orange Juice,Syrup)",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "cocktails_shakes",
    image: "tequila_sunrise",
  },
  {
    id: "cocktails-shakes-12",
    nameEn: "Special Mix - Non Alcoholic",
    nameFr: "Special Mix - Non Alcoholic",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "cocktails_shakes",
    image: "special_mix",
  },
  {
    id: "cocktails-shakes-13",
    nameEn: "Sex On The Beach",
    nameFr: "Sex On The Beach",
    descriptionEn: "(Vodka, Orange Juice, Syrup)",
    descriptionFr: "(Vodka, Orange Juice, Syrup)",
    price: 3000,
    category: "cocktails_shakes",
    image: "sex_on_the_beach",
  },
  {
    id: "cocktails-shakes-14",
    nameEn: "PINACOLADA (Rhum,Cocunut Cream, Pineapple Juice, Lime)",
    nameFr: "PINACOLADA (Rhum,Cocunut Cream, Pineapple Juice, Lime)",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "cocktails_shakes",
    image: "pinacolada",
  },
  {
    id: "cocktails-shakes-15",
    nameEn: "MYWAY SPECIAL LADIES",
    nameFr: "MYWAY SPECIAL LADIES",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "myway_special_ladies",
  },
  {
    id: "cocktails-shakes-16",
    nameEn: "MYWAY SPECIAL GENTLEMEN",
    nameFr: "MYWAY SPECIAL GENTLEMEN",
    descriptionEn: "",
    descriptionFr: "",
    price: 5500,
    category: "cocktails_shakes",
    image: "myway_special_gentlemen",
  },
  {
    id: "cocktails-shakes-17",
    nameEn: "Mojito Passion Fruit Remix",
    nameFr: "Mojito Passion Fruit Remix",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "mojito_passion",
  },
  {
    id: "cocktails-shakes-18",
    nameEn: "Mojito Mango Fruit Remix",
    nameFr: "Mojito Mango Fruit Remix",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "mojito_mango",
  },
  {
    id: "cocktails-shakes-18",
    nameEn: "Mojito Clementine Fruit Remix",
    nameFr: "Mojito Clementine Fruit Remix",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "mojito_clementine",
  },
  {
    id: "cocktails-shakes-19",
    nameEn: "Mojito (Rhum, Syrup, Soda, Mint Leaves)",
    nameFr: "Mojito (Rhum, Syrup, Soda, Mint Leaves)",
    descriptionEn: "",
    descriptionFr: "",
    price: 4000,
    category: "cocktails_shakes",
    image: "mojito",
  },
  {
    id: "cocktails-shakes-20",
    nameEn: "Milkshake",
    nameFr: "Milkshake",
    descriptionEn: "(Vanilla, Chocolate, Coffee)",
    descriptionFr: "(Vanilla, Chocolate, Coffee)",
    price: 3000,
    category: "cocktails_shakes",
    image: "milkshake",
  },
  {
    id: "cocktails-shakes-21",
    nameEn: "Mikolasone - Alcoholic",
    nameFr: "Mikolasone - Alcoholic",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "cocktails_shakes",
    image: "mikolasone",
  },
  {
    id: "cocktails-shakes-22",
    nameEn: "Fruit Punch - Non Alcoholic",
    nameFr: "Fruit Punch - Non Alcoholic",
    descriptionEn: "",
    descriptionFr: "",
    price: 3500,
    category: "cocktails_shakes",
    image: "fruit_punch",
  },
  {
    id: "cocktails-shakes-23",
    nameEn: "DOLCEZZA (Whipped Cream, Baileys, Vanilla Syrup)",
    nameFr: "DOLCEZZA (Crème fouettée, Baileys, Sirop de vanille)",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "dolcezza",
  },
  {
    id: "cocktails-shakes-24",
    nameEn: "DAIQUIRI (Rhum, Lime Juice,Syrup)",
    nameFr: "DAIQUIRI (Rhum, Jus de Citron Vert,Sirop)",
    descriptionEn: "",
    descriptionFr: "",
    price: 5000,
    category: "cocktails_shakes",
    image: "daiquiri",
  },
  {
    id: "cocktails-shakes-25",
    nameEn: "CUBA LIBRE (Rhum/Vodka, Coca-Cola, Lime Wedge)",
    nameFr: "CUBA LIBRE (Rhum/Vodka, Coca-Cola, Quart de Citron Vert)",
    descriptionEn: "",
    descriptionFr: "",
    price: 4500,
    category: "cocktails_shakes",
    image: "cuba_libre",
  },
  // Wines & Champagne
  {
    id: "wines-champagne-1",
    nameEn: "Agnor Red Wine",
    nameFr: "Agnor Red Wine",
    descriptionEn: "",
    descriptionFr: "",
    price: 12500,
    category: "wines_champagne",
    image: "agnor_red_wine",
  },
  {
    id: "wines-champagne-2",
    nameEn: "Bay Kloof Merlot",
    nameFr: "Bay Kloof Merlot",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "bay_kloof_merlot",
  },
  {
    id: "wines-champagne-3",
    nameEn: "Bronkhurst Cabernet Sauvignon",
    nameFr: "Bronkhurst Cabernet Sauvignon",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "wines_champagne",
    image: "bronkhurst_cabernet_sauvignon",
  },
  {
    id: "wines-champagne-4",
    nameEn: "Chantereau La Bibiere",
    nameFr: "Chantereau La Bibiere",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "chantereau_la_bibiere",
  },
  {
    id: "wines-champagne-5",
    nameEn: "Haut Medoc - Chateau Darcins,",
    nameFr: "Haut Medoc - Chateau Darcins,",
    descriptionEn: "",
    descriptionFr: "",
    price: 30000,
    category: "wines_champagne",
    image: "haut_medoc_chateau_darcins",
  },
  {
    id: "wines-champagne-6",
    nameEn: "Haut Medoc De Giscours",
    nameFr: "Haut Medoc De Giscours",
    descriptionEn: "",
    descriptionFr: "",
    price: 35000,
    category: "wines_champagne",
    image: "haut_medoc_de_giscours",
  },
  {
    id: "wines-champagne-7",
    nameEn: "MOET NECTAR",
    nameFr: "MOET NECTAR",
    descriptionEn: "",
    descriptionFr: "",
    price: 75000,
    category: "wines_champagne",
    image: "moet_nectar",
  },
  {
    id: "wines-champagne-8",
    nameEn: "Bellaire Rose Light",
    nameFr: "Bellaire Rose Light",
    descriptionEn: "",
    descriptionFr: "",
    price: 65000,
    category: "wines_champagne",
    image: "bellaire_rose",
  },
  {
    id: "wines-champagne-9",
    nameEn: "Veavue Cliquot",
    nameFr: "Veavue Cliquot",
    descriptionEn: "",
    descriptionFr: "",
    price: 70000,
    category: "wines_champagne",
    image: "veavue_cliquot",
  },
  {
    id: "wines-champagne-10",
    nameEn: "Croix Saint-Martin Bordeaux (Rose)",
    nameFr: "Croix Saint-Martin Bordeaux (Rose)",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "wines_champagne",
    image: "croix_saint_martin_bordeaux",
  },
  {
    id: "wines-champagne-11",
    nameEn: "MOET IMPERIAL",
    nameFr: "MOET IMPERIAL",
    descriptionEn: "",
    descriptionFr: "",
    price: 55000,
    category: "wines_champagne",
    image: "moet_imperial",
  },
  {
    id: "wines-champagne-12",
    nameEn: "Blu Nun",
    nameFr: "Blu Nun",
    descriptionEn: "",
    descriptionFr: "",
    price: 40000,
    category: "wines_champagne",
    image: "blu_nun",
  },
  {
    id: "wines-champagne-13",
    nameEn: "Château La Borne Bordeaux Moelleux",
    nameFr: "Château La Borne Bordeaux Moelleux",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "chateau_la_borne_bordeaux",
  },
  {
    id: "wines-champagne-14",
    nameEn: "Catherine De Beauvais (Red Wine Bordeaux 2018)",
    nameFr: "Catherine De Beauvais (Red Wine Bordeaux 2018)",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "catherine_de_beauvais",
  },
  {
    id: "wines-champagne-15",
    nameEn: "LOUISTON ROYAL (Moelleux)",
    nameFr: "LOUISTON ROYAL (Moelleux)",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "louiston_royal",
  },
  {
    id: "wines-champagne-16",
    nameEn: "Haut Medoc Chateau BARREYRES",
    nameFr: "Haut Medoc Chateau BARREYRES",
    descriptionEn: "",
    descriptionFr: "",
    price: 30000,
    category: "wines_champagne",
    image: "haut_medoc",
  },
  {
    id: "wines-champagne-17",
    nameEn: "Cote Bergerac (Moelleux)",
    nameFr: "Cote Bergerac (Moelleux)",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "wines_champagne",
    image: "cote_bergerac",
  },
  {
    id: "wines-champagne-18",
    nameEn: "Cabarnet D'anjout (Rose)",
    nameFr: "Cabarnet D'anjout (Rose)",
    descriptionEn: "",
    descriptionFr: "",
    price: 20000,
    category: "wines_champagne",
    image: "cabarnet_danjout",
  },
  {
    id: "wines-champagne-19",
    nameEn: "Bordeau Candely (Red Wine)",
    nameFr: "Bordeau Candely (Red Wine)",
    descriptionEn: "",
    descriptionFr: "",
    price: 15000,
    category: "wines_champagne",
    image: "bordeau_candely",
  },
  // Non-Alcoholic Beverages
  {
    id: "non-alcoholic-1",
    nameEn: "Red Bull",
    nameFr: "Red Bull",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "non_alcoholic_beverages",
    image: "red_bull",
  },
  {
    id: "non-alcoholic-2",
    nameEn: "VanPur Malt",
    nameFr: "VanPur Malt",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "non_alcoholic_beverages",
    image: "vanpur_malt",
  },
  {
    id: "non-alcoholic-3",
    nameEn: "MALTA",
    nameFr: "MALTA",
    descriptionEn: "",
    descriptionFr: "",
    price: 1500,
    category: "non_alcoholic_beverages",
    image: "malta",
  },
  {
    id: "non-alcoholic-4",
    nameEn: "Fanta",
    nameFr: "Fanta",
    descriptionEn: "",
    descriptionFr: "",
    price: 1500,
    category: "non_alcoholic_beverages",
    image: "fanta",
  },
  {
    id: "non-alcoholic-5",
    nameEn: "Alpha",
    nameFr: "Alpha",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "non_alcoholic_beverages",
    image: "alpha",
  },
  {
    id: "non-alcoholic-6",
    nameEn: "Tea Ginger",
    nameFr: "Tea Ginger",
    descriptionEn: "",
    descriptionFr: "",
    price: 1500,
    category: "non_alcoholic_beverages",
    image: "tea_ginger",
  },
  {
    id: "non-alcoholic-7",
    nameEn: "Sprite",
    nameFr: "Sprite",
    descriptionEn: "",
    descriptionFr: "",
    price: 1500,
    category: "non_alcoholic_beverages",
    image: "sprite",
  },
  {
    id: "non-alcoholic-8",
    nameEn: "Water",
    nameFr: "Water",
    descriptionEn: "0.5L",
    descriptionFr: "0.5L",
    price: 500,
    category: "non_alcoholic_beverages",
    image: "water",
  },
  {
    id: "non-alcoholic-9",
    nameEn: "Coca-Cola",
    nameFr: "Coca-Cola",
    descriptionEn: "can 33cl",
    descriptionFr: "can 33cl",
    price: 1500,
    category: "non_alcoholic_beverages",
    image: "coca_cola",
  },
  // Beers
  {
    id: "beers-1",
    nameEn: "Corona",
    nameFr: "Corona",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "corona",
  },
  {
    id: "beers-2",
    nameEn: "KISS",
    nameFr: "KISS",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "kiss",
  },
  {
    id: "beers-3",
    nameEn: "Smirnoff Ice",
    nameFr: "Smirnoff Ice",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "smirnoff_ice",
  },
  {
    id: "beers-4",
    nameEn: "Guiness (Small)",
    nameFr: "Guiness (Small)",
    descriptionEn: "",
    descriptionFr: "",
    price: 2500,
    category: "beers",
    image: "guiness_small",
  },
  {
    id: "beers-5",
    nameEn: "1664 Blanc Fruits Rouges",
    nameFr: "1664 Blanc Fruits Rouges",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "1664_blanc_fruits_rouges",
  },
  {
    id: "beers-6",
    nameEn: "Skoll",
    nameFr: "SKoll",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "skoll",
  },
  {
    id: "beers-7",
    nameEn: "HEINEKEN",
    nameFr: "HEINEKEN",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "beers",
    image: "heineken",
  },
  // Spirits & Liqueurs
  {
    id: "spirits-1",
    nameEn: "HENESSY VSOP",
    nameFr: "HENESSY VSOP",
    descriptionEn: "",
    descriptionFr: "",
    price: 75000,
    category: "spirits_liqueurs",
    image: "hennessy_vsop",
  },
  {
    id: "spirits-2",
    nameEn: "SHOT STANDARD",
    nameFr: "SHOT STANDARD",
    descriptionEn: "",
    descriptionFr: "",
    price: 1000,
    category: "spirits_liqueurs",
    image: "shot_standard",
  },
  {
    id: "spirits-3",
    nameEn: "SHOT HOT",
    nameFr: "SHOT HOT",
    descriptionEn: "",
    descriptionFr: "",
    price: 2000,
    category: "spirits_liqueurs",
    image: "shot_hot",
  },
  {
    id: "spirits-4",
    nameEn: "Glen MoRanGie 14",
    nameFr: "Glen MoRanGie 14",
    descriptionEn: "",
    descriptionFr: "",
    price: 75000,
    category: "spirits_liqueurs",
    image: "glen_morangie_14",
  },
  {
    id: "spirits-5",
    nameEn: "Baileys",
    nameFr: "Baileys",
    descriptionEn: "",
    descriptionFr: "",
    price: 30000,
    category: "spirits_liqueurs",
    image: "baileys",
  },
  {
    id: "spirits-6",
    nameEn: "Glen MoRanGie Original",
    nameFr: "Glen MoRanGie Original",
    descriptionEn: "",
    descriptionFr: "",
    price: 50000,
    category: "spirits_liqueurs",
    image: "glen_morangie_original",
  },
  {
    id: "spirits-7",
    nameEn: "Glen MoRanGie 12",
    nameFr: "Glen MoRanGie 12",
    descriptionEn: "",
    descriptionFr: "",
    price: 50000,
    category: "spirits_liqueurs",
    image: "glen_morangie_12",
  },
  {
    id: "spirits-8",
    nameEn: "HENESSEY VS 70CL",
    nameFr: "HENESSEY VS 70CL",
    descriptionEn: "",
    descriptionFr: "",
    price: 55000,
    category: "spirits_liqueurs",
    image: "hennessy_vs",
  },
  {
    id: "spirits-9",
    nameEn: "Black Label",
    nameFr: "Black Label",
    descriptionEn: "",
    descriptionFr: "",
    price: 40000,
    category: "spirits_liqueurs",
    image: "black_label",
  },
  {
    id: "spirits-10",
    nameEn: "MACALLAN triple cask",
    nameFr: "MACALLAN triple cask",
    descriptionEn: "",
    descriptionFr: "",
    price: 90000,
    category: "spirits_liqueurs",
    image: "macallan_triple_cask",
  },
  {
    id: "spirits-11",
    nameEn: "DEWARS 18",
    nameFr: "DEWARS 18",
    descriptionEn: "",
    descriptionFr: "",
    price: 90000,
    category: "spirits_liqueurs",
    image: "dewars_18",
  },
  {
    id: "spirits-12",
    nameEn: "DEWARS 12",
    nameFr: "DEWARS 12",
    descriptionEn: "",
    descriptionFr: "",
    price: 40000,
    category: "spirits_liqueurs",
    image: "dewars_12",
  },
];
